version: '3.9'

services:
  database:
    image: postgres
    container_name: dev-backend
    restart: always
    ports:
      - 5500:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123456789
      - POSTGRES_DB=backend-typescript-api
volumes:
  pgdata:
    driver: local
